template: Hello, %s!

defaultName: Stranger
jwtTokenSecret: dfwzsdzwh823zebdwdz772632gdsbd1

swagger:
  resourcePackage: com.huzzl.resources

server:
  applicationConnectors:
      - type: http
        port: 8080

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: devuser

  # the password
  password: demo123

  # the JDBC URL
  url: jdbc:postgresql://192.168.1.50/huzzldb

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

redis:
  # The redis server's address; required.
  endpoint: 192.168.1.50:6379
  # Auth password for redis server connection.  (default: null)
  password: demo1234
  # The minimum number of idle connections to maintain in the pool.  (default: 0)
  minIdle: 0
  # The maximum number of idle connections allowed in the pool.  (default: 0)
  maxIdle: 0
  # The maximum number of connections allowed in the pool.  (default: 1024)
  maxTotal: 1924
  # Enables SSL connection. (default: false)
  ssl: false
  # The configured timeout (in milliseconds) for redis connections in the connection pool.  (default: 2000)
  timeout: 2000
