template: Hello, %s!

defaultName: Stranger

jwtTokenSecret: ${JWT_TOKEN_SECRET}

swagger:
  resourcePackage: com.huzzl.resources
  schemes:
      - http
      - https

server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
      - type: http
        port: ${PORT}

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: ${JDBC_DATABASE_USERNAME}

  # the password
  password: ${JDBC_DATABASE_PASSWORD}

  # the JDBC URL
  url: jdbc:postgresql://${JDBC_DATABASE_URL}

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false


redis:
  # The redis server's address; required.
  endpoint: ${REDIS_ENDPOINT}
  # Auth password for redis server connection.  (default: null)
  password: ${REDIS_PASSWORD}
  # The minimum number of idle connections to maintain in the pool.  (default: 0)
  minIdle: 0
  # The maximum number of idle connections allowed in the pool.  (default: 0)
  maxIdle: 0
  # The maximum number of connections allowed in the pool.  (default: 1024)
  maxTotal: 1924
  # Enables SSL connection. (default: false)
  ssl: false
  # The configured timeout (in milliseconds) for redis connections in the connection pool.  (default: 2000)
  timeout: 2000